### ISSUE TITLE
成功部署后只显示𝐓𝐡𝐞 𝐔𝐬𝐞𝐫𝐧𝐚𝐦𝐞 𝐢𝐬 𝐍𝐨𝐭 𝐎𝐜𝐜𝐮𝐩𝐢𝐞𝐝 𝐛𝐲 𝐚𝐧𝐲𝐨𝐧𝐞

### ISSUE THREAD

**Issue by Kay-Gallagher** [SudoR2spr/Save-Restricted-Bot#1]
![image](https://github.com/user-attachments/assets/051065be-e1b5-4774-bb29-685fcfac8733)

但无效

**Comment by SudoR2spr** [comment]
> ![image](https://private-user-images.githubusercontent.com/79865121/372407204-051065be-e1b5-4774-bb29-685fcfac8733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTkwNTEsIm5iZiI6MTcyOTk1ODc1MSwicGF0aCI6Ii83OTg2NTEyMS8zNzI0MDcyMDQtMDUxMDY1YmUtZTFiNS00Nzc0LWJiMjktNjg1ZmNmYWM4NzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE2MDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMWJjN2NhZTAxOGZkY2RhYjY5NTc0OThjNTIyYmJkOTkxZDE1OWU0NjE3MTA4ZjAxMTliM2FlYWQxOGMxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y2nbbzOiTDSsB2_a3SbJScukvlIxT9HUQGOA1WxE6I0)
> 
> 但无效

FIXED
